Request Board Screen
Real-Dev-Squad/skill-tree-frontend pull request #10
Opened 2023-08-15 11:36 UTC by manish591

## Issue

closes #5

2023-08-20 14:16 UTC, bhtibrewal commented on src/components/RequestBoard/index.tsx
> +export default function RequestBoard() {
this should have been a page not a component

2023-08-20 14:19 UTC, bhtibrewal commented on src/components/RequestBoard/Icon.tsx
> +export default function Icon({ iconUrl, alt, width, height }: IconProps) {
why do we need this component?

2023-08-20 14:19 UTC, bhtibrewal commented on src/components/RequestBoard/Input.tsx
> +export default function Input({ placeholder, type }: InputProps) {
this should have been a common component

2023-08-20 14:19 UTC, bhtibrewal commented on src/components/RequestBoard/MemberVotesDetails/Avatar.tsx
> +export default function Avatar({ url, alt, width, height }: AvatarProps) {
same common component

2023-08-20 14:21 UTC, bhtibrewal commented on src/constants/images.ts
> +const NEXT_ARROW_ICON = "/next-arrow-icon.svg";
use react-icons library, we cannot keep on adding icon files

2023-08-20 14:27 UTC, bhtibrewal reviewed
added a few comments please look into them and add UI screenshots in the PR

2023-08-20 14:31 UTC, manish591 commented on src/components/RequestBoard/Input.tsx
> +export default function Input({ placeholder, type }: InputProps) {
I don't understand what you meant by `common`. Could you please explain? Did you mean a generic component that can be used in other parts of the app with more configurations?

2023-08-20 14:50 UTC, manish591 commented on src/components/RequestBoard/index.tsx
> +export default function RequestBoard() {
What will be the page route name?

2023-08-26 05:45 UTC, apurvkhare commented on src/components/VotesListModal/VotesDescription.tsx
> +                <Avatar name="Manish" src={src} width={40} height={40} />
I believe this should be `name={name}`

2023-08-27 10:39 UTC, bhtibrewal commented on src/components/Avatar/Avatar.tsx
> +export default function Avatar({ src, name, width, height }: AvatarProps) {
please have a default height, and width for the avatar, and instead of taking height width prop I think it would be better to have size prop like 
`size: sm, md, lg`

2023-08-27 10:40 UTC, bhtibrewal commented on src/components/Avatar/Avatar.tsx
> +};
why are we writing inline style, we have tailwind classes

2023-08-27 10:41 UTC, bhtibrewal commented on src/components/Avatar/Avatar.tsx
> +                    alt={name}
```suggestion
<Image {...props} />
```

2023-08-27 10:44 UTC, bhtibrewal commented on src/components/Button/Button.tsx
> +    if (roundness) {
have a default roundness and variant so don't need `if (roundness)`

2023-08-27 10:47 UTC, bhtibrewal commented on src/components/Button/Button.tsx
> +        }
use object like 
```
defaultVarients.roundness = variantsStyles.roundness[ROUNDNESS_VARIANTS.PILL]
```

2023-08-27 10:48 UTC, bhtibrewal commented on src/components/Input/Input.tsx
> +    }
same suggestions as given in button component

2023-08-27 10:52 UTC, bhtibrewal commented on src/components/Input/Input.tsx
> +                />
```suggestion
                <input
                    data-testid="input"
                    id={label}
                    type={type}
                    name={name}
                    value={value}
                    placeholder={placeholder}
                    disabled={disabled}
                    className={"placeholder:text-black-light outline-none bg-transparent w-full", props.inputClassName}
                />
```

2023-08-27 15:34 UTC, satyam73 requested changes
Requested few changes rest all looks good to me.

2023-08-27 15:34 UTC, satyam73 commented on src/components/Avatar/Avatar.tsx
> +};
+1

2023-08-27 15:34 UTC, satyam73 commented on src/components/Avatar/Avatar.tsx
> +                    {name.charAt(0).toUpperCase()}
try using variable at top and add this value in that variable and add the variable here

2023-08-27 15:34 UTC, satyam73 commented on src/components/Button/Button.tsx
> +    const defaultVarients = {
NIT - typo in defaultVariants

2023-08-27 15:34 UTC, satyam73 commented on src/components/Input/Input.tsx
> +            {iconPosition === "right" || !iconPosition ? <span data-testid="input-icon-right">{icon}</span> : null}
you can pass iconPosition as default props so that you don't have to check || case here

2023-08-27 15:34 UTC, satyam73 commented on src/components/SkillLabel/SkillLabel.tsx
> +    const defaultVarients = {
type here*, it will be `defaultVariants`

2023-08-27 15:34 UTC, satyam73 commented on src/components/VotesListModal/VotesDescription.tsx
> +                <Avatar name="Manish" src={src} width={40} height={40} />
+1

2023-08-28 15:21 UTC, satyam73 approved these changes
LGTM

2023-08-29 15:02 UTC, bhtibrewal approved these changes
LGTM

2023-08-29 17:29 UTC, merged