create UI for the endorsement details slide over #6
Real-Dev-Squad/skill-tree-frontend pull request #11
Opened 2023-08-17 16:50 UTC by suhaasya

2023-08-23 15:06 UTC, bhtibrewal commented on src/app/page.tsx
> +import * as drawerData from "../../__mocks__/drawer.json";
```suggestion
import * as endorsementDetails from "../../__mocks__/drawer.json";
```

2023-08-23 15:07 UTC, bhtibrewal commented on src/app/page.tsx
> +            </Drawer>
```suggestion
           <EndorsementDetailsSlideOver endorsementId={endorsement.id}/>
```

2023-08-23 15:25 UTC, bhtibrewal commented on src/components/card/Card.tsx
> +            <span>
if the name is seeMoreBtn, I think it should be a button, will also be good for accesibility

2023-08-23 15:25 UTC, bhtibrewal commented on src/components/card/Card.tsx
> +                ... <span className="text-blue cursor-pointer">see more</span>
functionality for see more?

2023-08-23 15:30 UTC, bhtibrewal commented on src/components/card/CardList.tsx
> +    );
i am not sure what is the need to make this as a separate component

2023-08-23 15:33 UTC, bhtibrewal commented on src/components/tag/Tag.tsx
> +            <span className={`text-yellow-dark`}>{children}</span>
why are we using 2 span tags here?

2023-08-23 15:34 UTC, suhaasya commented on src/components/card/Card.tsx
> +                ... <span className="text-blue cursor-pointer">see more</span>
i actually have a doubt in that. it should render all the description there only. or it will route to some page??

2023-08-23 15:35 UTC, suhaasya commented on src/components/card/CardList.tsx
> +    );
should i remove it then?

2023-08-23 15:39 UTC, suhaasya commented on src/components/tag/Tag.tsx
> +            <span className={`text-yellow-dark`}>{children}</span>
i used it to make text look in the exact center. i guess it looks similar without span. will remove it.

2023-08-23 15:41 UTC, suhaasya commented on src/components/card/Card.tsx
> +const Card = ({ name, description }: CardProps) => {
how about EndorsementCard??

2023-08-23 15:41 UTC, suhaasya commented
thank you. will work on it.

2023-08-23 18:52 UTC, suhaasya commented on src/app/page.tsx
> +import * as drawerData from "../../__mocks__/drawer.json";
updated please check.

2023-08-23 18:52 UTC, suhaasya commented on src/app/page.tsx
> +            </Drawer>
updated please check

2023-08-23 18:52 UTC, suhaasya commented on src/components/button/Button.tsx
> +            : `bg-[${color}]`;
updated please check

2023-08-23 18:53 UTC, suhaasya commented on src/components/card/Card.tsx
> +            <span>
updated.

2023-08-26 17:07 UTC, yesyash requested changes

2023-08-26 17:07 UTC, yesyash commented on src/components/endorsementCard/EndorsementCard.tsx
> +        ) : null;
- I think a better way to handle this could be to have this ternary at line `29` while the boolean condition could be saved in the `toggleDescButton`.

2023-08-26 17:07 UTC, yesyash commented on src/hooks/useOutsideClick.ts
- Instead of creating a hook to detect outside click, what if we have an `overlay` on top of all elements and the `endorsementSlideOver` on top of all of this such that when you click on the `overlay` we close `endorsementSlideOver`. What do you think?

2023-08-26 17:07 UTC, yesyash commented on src/utils/stringToRegex.ts
- What is this utility for?

2023-08-26 17:08 UTC, yesyash commented
- Please verify if the design link mentioned in the ticket is correct. 
I think this was the finalized design : [Design link](https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=201%3A2607&mode=design&t=EJCYU2fvzInPMDQe-1)

2023-08-27 04:39 UTC, suhaasya commented on __tests__/index.test.tsx
no. actually it was from earlier pr for test setup. i made this branch from test setup branch so there wont be any merge conflicts. should i remove it??

2023-08-27 04:41 UTC, suhaasya commented on src/hooks/useOutsideClick.ts
we can do that. it simple and easy to understand for other developers too. 
i seen this somewhere so though to implement here.

2023-08-27 04:46 UTC, suhaasya commented on src/utils/stringToRegex.ts
while writing tests. when we use getByText for long text or text which have special characters we need to convert that text to regex. we can do that by following code

```
new RegExp(str, "i")
```
what do you suggest to keep it as function
or use above line everytime??

2023-08-27 15:32 UTC, bhtibrewal approved these changes
LGTM

2023-08-31 07:26 UTC, Pratiyushkumar requested changes
please divide your PR into small PR's as this PR is too long to review.

2023-08-31 15:58 UTC, suhaasya commented
hey @Pratiyushkumar  I can do it. 
but wont it be more work?  as bhavika and yash already reviewed it. 
And i only need one approval for getting this merge.
just wanna confirm. should i do it???

2023-08-31 16:06 UTC, Pratiyushkumar commented
> 

Yes please do it, It's actually a very long PR for me to review 
@bhtibrewal  @yesyash  don't you think this PR needs to be braked as the PR has more than 2k lines

2023-08-31 17:40 UTC, bhtibrewal commented
> > 
> 
> Yes please do it, It's actually a very long PR for me to review @bhtibrewal @yesyash don't you think this PR needs to be braked as the PR has more than 2k lines

I have looked into the PR, It is 2K+ lines due to some dependencies addition, so `yarn.lock` is making it seem long, @Pratiyushkumar if you don't have any other suggestions,  please approve the PR

2023-09-01 11:47 UTC, Pratiyushkumar commented on src/utils/stringToRegex.ts
is this really required to make a separate utility file for regex, are we sure to use this for other components in the future?

2023-09-01 11:47 UTC, Pratiyushkumar commented on src/components/tag/Tag.tsx
> +            role="tag"
does this role="tag" exist??? is this the correct role we are providing to span tag??

2023-09-01 11:47 UTC, Pratiyushkumar commented on __tests__/components/tag/Tag.test.tsx
> +        const tagElement = getByText("Atomic");
please add proper test case names, and give some sensible names for others to understand.

2023-09-01 11:48 UTC, Pratiyushkumar commented
Also resolve the merge conflict in your PR

2023-09-01 17:09 UTC, suhaasya commented on __tests__/components/tag/Tag.test.tsx
> +        const tagElement = getByText("Atomic");
sorry. changed it. please check if that one is correct. also removed one test as it was unnecessary.

2023-09-01 17:10 UTC, suhaasya commented on src/components/tag/Tag.tsx
> +            role="tag"
its attribute we can assign it value. btw removed it. also updated test.

2023-09-01 17:11 UTC, suhaasya commented on src/utils/stringToRegex.ts
didnt found any where we can use it. so removed it.

2023-09-01 19:20 UTC, yesyash commented on __tests__/index.test.tsx
- yes please

2023-09-01 19:26 UTC, yesyash commented on src/utils/stringToRegex.ts
- I think the right time to abstract it into a function would be when you have repetitive logic related to regex which was being used in multiple places, in the current form I don't see a need for making this into a function.

2023-09-01 19:33 UTC, yesyash requested changes

2023-09-01 19:33 UTC, yesyash commented on src/components/button/Button.tsx
- Do we not already have a button component in `src/components/Button` why are we creating a new one here?

2023-09-01 19:34 UTC, yesyash commented on src/utils/stringToRegex.ts
@suhaasya keeping this comment unresolved for you to see, you can mark it resolved once viewed, and if you don't have other questions.

2023-09-01 19:36 UTC, yesyash commented
> > 
> 
> Yes please do it, It's actually a very long PR for me to review @bhtibrewal @yesyash don't you think this PR needs to be braked as the PR has more than 2k lines

- Breaking the tests into their own PR could have drastically cut down on the scope and the size of the pr @suhaasya, try it from next time.

2023-09-02 04:32 UTC, suhaasya commented on src/components/button/Button.tsx
when i started working. there was no button component. so i created my own. but i now modified it and deleted which i created.

2023-09-02 04:34 UTC, suhaasya commented on src/utils/stringToRegex.ts
i have also seen design didnt find anywhere we can use it. so removed it.

2023-09-02 04:42 UTC, suhaasya commented
> > > 
> > 
> > 
> > Yes please do it, It's actually a very long PR for me to review @bhtibrewal @yesyash don't you think this PR needs to be braked as the PR has more than 2k lines
> 
>     * Breaking the tests into their own PR could have drastically cut down on the scope and the size of the pr @suhaasya, try it from next time.

sure. I will keep this in mind for future PRs. Thank you.

2023-09-02 05:23 UTC, yesyash approved these changes

2023-09-02 08:48 UTC, bhtibrewal approved these changes

2023-09-02 08:48 UTC, merged