Update README.md
Real-Dev-Squad/skill-tree-frontend pull request #117
Opened 2024-09-15 11:00 UTC by sunilk429

1. Added setup for env.local
2. Added update for the hosts file

Date: 15-09-2024

Developer Name: Sunil Kumar

---

## Issue Ticket Number

## Description

Updated setup for local.env and setting proxy locally by updating hosts file
### Documentation Updated?

- [x] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [ ] Yes
- [x] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-09-16 16:39 UTC, yesyash requested changes

2024-09-16 16:39 UTC, yesyash commented on README.md
> +    ```
- when writing a readme with instructions to set up the repository make sure that you take the user to the end i.e. a link where they can see the app running. 
here is a small but efficient example: 
    - [website status](https://github.com/Real-Dev-Squad/website-status?tab=readme-ov-file#setup-and-running-locally)

2024-09-16 16:39 UTC, yesyash commented on README.md
> +    ```
- also do not add the steps to change etc hosts directly here, link to the `avoiding cors during development` document.

2024-09-16 17:26 UTC, sunilk429 commented on README.md
> +    ```
Thanks Yash for your feedback, I will update this

2024-09-16 18:57 UTC, sunilk429 commented on README.md
> +    ```
I have made changes, Please if you could review the changes

2024-09-17 20:16 UTC, yesyash approved these changes

2024-09-17 20:19 UTC, yesyash requested changes

2024-09-17 20:19 UTC, yesyash commented on README.md
> +   ```
- remove this

2024-09-17 20:19 UTC, yesyash commented on README.md
> +7. **Run Tests**:
- put this under a heading 

### Testing
- To run tests run the following command:
```sh
npm run test
```

2024-09-18 02:49 UTC, sunilk429 commented on README.md
> +7. **Run Tests**:
I have added changes, if you could please review Yash

2024-09-18 10:46 UTC, yesyash approved these changes

2024-09-18 18:36 UTC, prakashchoudhary07 approved these changes

2024-09-18 18:57 UTC, merged