Request Board Screen #2
Real-Dev-Squad/skill-tree-frontend pull request #15
Opened 2023-08-30 10:55 UTC by manish591

2023-08-31 06:58 UTC, manish591 commented
Tests for the hook `useScrollDirection` are not implemented. Because React testing library tests Run in a jsdom environment, scroll-based events are not working. 

Please suggest how to test this.

2023-09-03 13:29 UTC, kotesh-arya reviewed
Great Work with the UI 🙌🏻

2023-09-03 13:29 UTC, kotesh-arya commented on src/components/RequestBoardTable/BoardDetailsRow.tsx
> +    colorScheme: "green" | "yellow" | "blue";
can you explain a bit about considering values instead of their type ?

2023-09-03 13:29 UTC, kotesh-arya commented on src/components/Wrapper/Wrapper.tsx
NIT: How about making this file name `wrapper.tsx` a bit more self-explanatory ?

2023-09-03 13:29 UTC, kotesh-arya commented on __tests__/Unit/Componets/AvatarGroup/AvatarGroup.test.tsx
> +    it("should show the remaing avatar text 1", function () {
Please make this test name more descriptive and obvious

2023-09-03 18:32 UTC, satyam73 requested changes

2023-09-03 18:32 UTC, satyam73 commented on src/components/RequestBoardTable/index.tsx
> +                {requestBoardData.map((skillItem, index) => {
move this into constant a use that constant variable here

2023-09-03 18:32 UTC, satyam73 commented on src/components/VotesListModal/index.tsx
> +                    {votes.map((vote) => {
same as above

2023-09-05 20:24 UTC, manish591 commented on src/components/Wrapper/Wrapper.tsx
I would prefer to create a separate folder for each component.

2023-09-08 18:38 UTC, satyam73 requested changes

2023-09-08 18:38 UTC, satyam73 commented on src/components/RequestBoardTable/index.tsx
> +function renderBoardDetailsRow() {
```suggestion
const renderBoardDetailsRow = requestBoardData.map((skillItem, index) => {
        return <BoardDetailsRow key={skillItem.id} {...skillItem} colorScheme={SKILL_LABEL_COLOR_MAPPING[index % 6]} />;
    });
```

2023-09-08 18:38 UTC, satyam73 commented on src/components/RequestBoardTable/index.tsx
> +            <div className="mt-12 lg:mt-4 grid grid-cols-1 gap-8 lg:gap-0">{renderBoardDetailsRow()}</div>
```suggestion
            <div className="mt-12 lg:mt-4 grid grid-cols-1 gap-8 lg:gap-0">{renderBoardDetailsRow}</div>
```

2023-09-08 18:38 UTC, satyam73 commented on src/components/VotesListModal/index.tsx
> +function renderVotes(votes: VotesTypes[]) {
```suggestion
function renderVotes<type here> = votes.map((vote) => {
        return (
            <VotesDescription
                key={vote.name}
                src={vote.img}
                name={vote.name}
                date={vote.date}
                description={vote.reason}
            />
        );
    });
```

2023-09-09 18:28 UTC, manish591 commented on src/components/VotesListModal/index.tsx
> +function renderVotes(votes: VotesTypes[]) {
Please check the code if I have understood your changes correctly. I can't create this constant outside the component body as `votes` are not available in the global scope.

2023-09-18 09:42 UTC, satyam73 requested changes

2023-09-18 09:42 UTC, satyam73 commented on src/components/VotesListModal/index.tsx
> +    const renderVotes = votes.map((vote) => {
instead of using return you can do something like this :
```javascript
array.map((item)=> (<YourComponent />));
```

2023-09-18 09:42 UTC, satyam73 commented on src/components/RequestBoardTable/index.tsx
> +const renderBoardDetailsRow = requestBoardData.map((skillItem, index) => {
instead of using return you can do something like this :
```javascript
array.map((item)=> (<YourComponent />));
```

2023-09-23 18:26 UTC, BhavikaTibrewal reviewed
checking i can leave comment

2023-09-24 06:58 UTC, satyam73 approved these changes
LGTM

2023-09-25 02:59 UTC, kotesh-arya approved these changes

2023-09-25 07:49 UTC, merged