Feature/unit test shimmer
Real-Dev-Squad/skill-tree-frontend pull request #152
Opened 2024-10-06 10:11 UTC by sunilk429

## Date: 6th October, 2024

## Developer Name: Sunil Kumar 

---

## Issue Ticket Number

#148 
## Description

Added unit tests for `Shimmer` component
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Test Coverage
<details>
<summary>Screenshot 1</summary>

<img width="752" alt="shimmer" src="https://github.com/user-attachments/assets/cb7be5da-ac3d-426e-8abd-40a5b2d66761">

</details>

2024-10-08 18:21 UTC, yesyash requested changes

2024-10-08 18:21 UTC, yesyash commented on src/__tests__/unit/components/Shimmer.test.tsx
> +    it("renders without crashing", () => {
- how can this crash?

2024-10-08 19:15 UTC, sunilk429 commented on src/__tests__/unit/components/Shimmer.test.tsx
> +    it("renders without crashing", () => {
I mean, should render as expected, should have choose better phrase, `render's correctly` or just `renders`, will update it to `renders`

2024-10-10 16:31 UTC, yesyash approved these changes

2024-10-10 17:45 UTC, iamitprakash approved these changes

2024-10-10 17:45 UTC, merged