Feature/endors
Real-Dev-Squad/skill-tree-frontend pull request #23
Opened 2023-10-11 09:46 UTC by Pratiyushkumar

2023-10-11 15:17 UTC, Pratiyushkumar commented on src/components/DropDown/index.tsx
> +import { Menu, Transition } from "@headlessui/react";
no sorry, I forgot to ask permission for it, can we not use this headlessUi please I searched on Google but did not get a better approach for it or else can you please suggest a better solution if headlessUi is not allowed to use?
Also please let me know the reason of not using headlessUI

2023-10-11 15:27 UTC, bhtibrewal commented on src/components/DropDown/index.tsx
> +import { Menu, Transition } from "@headlessui/react";
instead of now asking for a reason to not use it, the right approach is to propose it before it with a reason to use

No, we will not be going ahead with headless UI now as we already have many pieces of our UI already built using tailwind

2023-10-11 15:28 UTC, bhtibrewal commented on src/components/DropDown/index.tsx
> +export default function DropDown() {
please use ES6

2023-10-11 15:29 UTC, bhtibrewal commented on src/components/DropDown/index.tsx
> +    function classNames(...args: string[]) {
please move to a util file

2023-10-11 19:40 UTC, Pratiyushkumar commented on src/components/DropDown/index.tsx
> +export default function DropDown() {
done

2023-10-11 19:40 UTC, Pratiyushkumar commented on src/components/DropDown/index.tsx
> +    function classNames(...args: string[]) {
removed

2023-10-11 19:46 UTC, Pratiyushkumar commented on src/components/DropDown/index.tsx
> +import { Menu, Transition } from "@headlessui/react";
fixed

2023-10-12 07:22 UTC, iamitprakash approved these changes

2023-10-14 08:46 UTC, bhtibrewal commented on src/pages/endorsements/index.tsx
> +                        <button className=" flex items-center p-2 rounded  w-[120px] text-[#F43F5E] bg-[#FFF1F2]">
please create tailwind color variable for these colors, for w-use the closest width class, if possible
ex : `w-32`

2023-10-14 08:47 UTC, bhtibrewal requested changes
left few comments, also i don't see tests written for the code

2023-10-14 09:32 UTC, Pratiyushkumar commented on src/pages/endorsements/index.tsx
> +                        <button className=" flex items-center p-2 rounded  w-[120px] text-[#F43F5E] bg-[#FFF1F2]">
color variable name used but for w and h I don't think there is an issue in customized value because that depends on our requirement and according to our requirement I have used customized value.

2023-10-14 09:33 UTC, Pratiyushkumar commented
> left few comments, also i don't see tests written for the code

tests are already written

2023-10-14 14:07 UTC, bhtibrewal approved these changes

2023-10-14 17:17 UTC, iamitprakash approved these changes

2023-10-14 17:25 UTC, merged