Nextjs 13 setup
Real-Dev-Squad/skill-tree-frontend pull request #3
Opened 2023-05-28 04:45 UTC by arpit01923

1. Added eslint
2. Prettier 
3. Pre-commit hooks

Issue: #1

2023-05-28 05:46 UTC, bhtibrewal requested changes

2023-05-28 05:46 UTC, bhtibrewal commented on src/app/page.tsx
> +        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dar
please remove the file, code and images that is will not be need

2023-05-28 05:47 UTC, bhtibrewal reviewed
I cannot find the pre-commit hook, and also add a PR template to the project

2023-05-29 02:24 UTC, arpit01923 commented on src/app/page.tsx
> +        <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dar
Removed unnecessary, image and code

2023-07-12 15:22 UTC, bhtibrewal approved these changes
LGTM

2023-07-12 15:39 UTC, RitikJaiswal75 requested changes

2023-07-12 15:39 UTC, RitikJaiswal75 commented on .vscode/settings.json
I think .vscode should be in gitignore, we do not want modifying developers' vs code setting

2023-07-12 15:39 UTC, RitikJaiswal75 commented on package.json
Please segregate dependencies and dev dependencies properly

2023-07-12 15:39 UTC, RitikJaiswal75 commented on pull_request_template.md
Do we want all of our pull requests to this repo to look like this?
If no, do we need this file?

Description here is too specific to this pr its not generic to be made a template and enforce it over all developers.

2023-07-12 15:39 UTC, RitikJaiswal75 commented on src/app/globals.css
lets set the padding and margin to 0 here for root.

2023-07-12 15:39 UTC, RitikJaiswal75 commented on tsconfig.json
can we add an outdir here?
or is it managed by next js automatically?

2023-07-15 07:33 UTC, arpit01923 commented on .vscode/settings.json
Added .vscode in gitignore

2023-07-15 07:33 UTC, arpit01923 commented on package.json
Segregated dependencies and dev dependencies

2023-07-15 07:35 UTC, arpit01923 commented on src/app/globals.css
Added padding and margin to 0

2023-07-15 07:38 UTC, arpit01923 commented on tsconfig.json
In a Next.js project, the output directory (outdir) is managed automatically.

2023-07-15 07:45 UTC, arpit01923 commented on pull_request_template.md
A standardized template for pull requests can provide clarity and consistency in the information shared during the review process.
If the template doesn't add value to your team's workflow, I will  removing the **pull_request_template.md**

2023-07-15 09:36 UTC, RitikJaiswal75 commented on pull_request_template.md
I agree with having a template, but it should be generic. The one here is very specific to your PR.

2023-07-15 09:37 UTC, RitikJaiswal75 commented on .vscode/settings.json
but the file is still present, remove it from the pull

2023-07-15 15:30 UTC, arpit01923 commented on .vscode/settings.json
Removed **.vscode** @RitikJaiswal75

2023-07-15 15:31 UTC, arpit01923 commented on pull_request_template.md
Ok got it @RitikJaiswal75. Removed the file

2023-07-15 16:31 UTC, bhtibrewal commented on pull_request_template.md
```
### Issue:

### Description:

### Anything you would like to inform the reviewer about:

### Dev Tested:
- [ ] Yes

### Test Stats

### Images/video of the change:

### Follow-up Issues (if any)
```

please add this PR template

2023-07-18 22:17 UTC, RitikJaiswal75 approved these changes

2023-07-20 04:06 UTC, vvaibhavdesai approved these changes

2023-07-22 04:50 UTC, bhtibrewal approved these changes

2023-07-22 04:51 UTC, merged